(require 'package)                                                                                                                                                                                                 
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)                                                                                                                                       
;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`                                                                                                                
;; and `package-pinned-packages`. Most users will not need or want to do this.                                                                                                                                     
;;(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)                                                                                                                       
(package-initialize)                                                                                                                                                                                               
                                                                                                                                                                                                                   
(load-theme 'afternoon t)                                                                                                                                                                                          
(global-display-line-numbers-mode)                                                                                                                                                                                 
(desktop-save-mode 1)                                                                                                                                                                                              
(global-set-key (kbd "C-x w") 'menu-bar-open)                                                                                                                                                                      
;;(setq x-select-enable-clipboard t)                                                                                                                                                                               
;;(setq select-enable-clipboard t)                                                                                                                                                                                 
(custom-set-variables                                                                                                                                                                                              
 ;; custom-set-variables was added by Custom.                                                                                                                                                                      
 ;; If you edit it by hand, you could mess it up, so be careful.                                                                                                                                                   
 ;; Your init file should contain only one such instance.                                                                                                                                                          
 ;; If there is more than one, they won't work right.                                                                                                                                                              
 '(custom-safe-themes                                                                                                                                                                                              
   '("57e3f215bef8784157991c4957965aa31bac935aca011b29d7d8e113a652b693" "3d4df186126c347e002c8366d32016948068d2e9198c496093a96775cc3b3eaa" default))                                                               
 '(ispell-dictionary nil)                                                                                                                                                                                          
 '(package-selected-packages                                                                                                                                                                                       
   '(afternoon-theme abyss-theme company ## eglot cmake-mode php-mode neotree jsonrpc go-mode flymake)))                                                                                                           
(custom-set-faces                                                                                                                                                                                                  
 ;; custom-set-faces was added by Custom.                                                                                                                                                                          
 ;; If you edit it by hand, you could mess it up, so be careful.                                                                                                                                                   
 ;; Your init file should contain only one such instance.                                                                                                                                                          
 ;; If there is more than one, they won't work right.                                                                                                                                                              
 )                                                                                                                                                                                                                 
(add-to-list 'load-path "/some/path/neotree")                                                                                                                                                                      
(require 'neotree)                                                                                                                                                                                                 
(global-set-key (kbd "C-x e") 'neotree-toggle)                                                                                                                                                                     
(electric-pair-mode 1)                                                                                                                                                                                             
(setq-default neo-show-hidden-files t)                                                                                                                                                                             
                                                                                                                                                                                                                   
;;(add-to-list 'eglot-server-programs '(foo-mode . ("foo-language-server" "--args")))                                                                                                                              
(add-hook 'after-init-hook 'global-company-mode)                                                                                                                                                                                           
